routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('products', 'ProductController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name', 'detail'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use phpDocumentor\Reflection\PseudoTypes\True_;
use Yajra\DataTables\Facades\DataTables;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $products = Product::latest()->get();

            return Datatables::of($products)
                ->addIndexColumn()
                ->addColumn('action', function($product) {
                    $btn = '<button class="btn btn-primary btn-sm editProduct" type="button" data-id="'.$product->id.'">Edit</button>';
                    $btn = $btn.' <button class="btn btn-danger btn-sm deleteProduct" type="button" data-id="'.$product->id.'">Delete</button>';

                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        $title = 'Product CRUD by Ajax';

        return view('products.index', compact('title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Product::updateOrCreate(
            ['id' => $request->id],
            [
                'name' => $request->name,
                'detail' => $request->detail
            ]
        );

        return response()->json(['success' => 'Product saved successfully.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return response()->json($product);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return response()->json(['success' => 'Product deleted successfully.']);
    }
}

resources/views/products/index.blade.php
@extends('products.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="float-left">
                <h2>Laravel 7 - {{ $title }}</h2>
            </div>
            <div class="float-right">
                <button class="btn btn-success" type="button" id="createNewProduct">
                    Create New Product
                </button>
            </div>
        </div>
    </div>

    <table class="table table-bordered" id="productsDatatable" width="100%">
        <thead>
            <tr>
                <th>N°</th>
                <th>Name</th>
                <th>Details</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>

    <!-- The Modal -->
    <div class="modal fade" id="productModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title" id="productModalTitle"></h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <!-- Modal body -->
                <form action="" method="post" id="productForm">
                <div class="modal-body">
                    <input type="hidden" name="id" id="id">
                    <div class="form-group">
                        <label for="name"><strong>Name</strong></label>
                        <input class="form-control" type="text" name="name" id="name" placeholder="Enter product name">
                    </div>
                    <div class="form-group">
                        <label for="detail"><strong>Details</strong></label>
                        <textarea class="form-control" name="detail" id="detail" placeholder="Enter product details"></textarea>
                    </div>
                </div>
                <!-- Modal footer -->
                <div class="modal-footer">
                    <input class="btn btn-primary" type="submit" value="Submit">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
<script type="text/javascript">
    $(document).ready(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var products_datatable = $('#productsDatatable').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('products.index') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                {data: 'name', name: 'name'},
                {data: 'detail', name: 'detail'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        });

        $('#createNewProduct').click(function(event) {
            $('#productModalTitle').text('Create Product');
            $('#productModal').modal('show');
        });

        $('#productsDatatable tbody').on('click', '.editProduct', function(event) {
            var product_id = $(this).data('id');

            $.ajax({
                url: '{{ route("products.edit", ":id") }}'.replace(':id', product_id),
                type: "GET",
                data: $('#productForm').serialize(),
                datatype: 'json',
                success: function(data) {
                    $('#productForm').trigger('reset');
                    $('#productModalTitle').text('Edit Product');
                    $('#id').val(data.id);
                    $('#name').val(data.name);
                    $('#detail').val(data.detail);
                    $('#productModal').modal('show');
                },
                error: function(data) {
                    alert('Error: ' + JSON.stringify(data));
                    products_datatable.draw();
                }
            });
        });

        $('#productForm').submit(function(event) {
            event.preventDefault();

            $.ajax({
                url: "{{ route('products.store') }}",
                type: "POST",
                data: $('#productForm').serialize(),
                datatype: 'json',
                success: function(data) {
                    $('#productModal').modal('hide');
                    $('#productForm').trigger('reset');
                    $('#id').val("");
                    products_datatable.draw();
                },
                error: function(data) {
                    alert('Error: ' + JSON.stringify(data));
                    products_datatable.draw();
                }
            });
        });

        $('#productsDatatable tbody').on('click', '.deleteProduct', function(event) {
            var product_id = $(this).data('id');

            var delete_product = confirm('Are you sure want to delete?');

            if (delete_product == true) {
                $.ajax({
                    url: '{{ route("products.destroy", ":id") }}'.replace(':id', product_id),
                    type: "DELETE",
                    datatype: 'json',
                    success: function(data) {
                        products_datatable.draw();
                    },
                    error: function(data) {
                        alert('Error: ' + JSON.stringify(data));
                        products_datatable.draw();
                    }
                });
            } else {
                products_datatable.draw();
            }
        });
    });
</script>
@endsection

resources/views/products/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
    <title>Laravel 7 - {{ $title }}</title>
</head>
<body>
    <div class="container mt-3">
        @yield('content')
    </div>
</body>
@yield('scripts')
</html>